U3RazasPerros/Models/Razas.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace U3RazasPerros.Models
{
    public partial class Razas
    {
        public uint Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string OtrosNombres { get; set; }
        public int IdPais { get; set; }
        public float PesoMin { get; set; }
        public float PesoMax { get; set; }
        public float AlturaMin { get; set; }
        public float AlturaMax { get; set; }
        public int EsperanzaVida { get; set; }

        public virtual Paises IdPaisNavigation { get; set; }
        public virtual Caracteristicasfisicas Caracteristicasfisicas { get; set; }
    }
}

U3RazasPerros/Areas/Admin/Controllers/RazasController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using U3RazasPerros.Areas.Admin.Models;
using U3RazasPerros.Models;

namespace U3RazasPerros.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RazasController : Controller
    {
        public perrosContext Context { get; }
        public IWebHostEnvironment Host { get; }

        public RazasController(perrosContext context, IWebHostEnvironment host)
        {
            Context = context;
            Host = host;
        }

        public IActionResult Index()
        {
            IEnumerable<Razas> razas = Context.Razas.OrderBy(x=>x.Nombre);
            return View(razas);
        }

        public IActionResult Agregar()
        {
            return View(new RazaCRUDViewModel {
                Paises = Context.Paises.OrderBy(x => x.Nombre)
            });
        }

        [HttpPost]
        public IActionResult Agregar(RazaCRUDViewModel vm, IFormFile imagen)
        {
            if (!Verificacion(vm, out string m))
            {
                ModelState.AddModelError("", m);
                vm.Paises = Context.Paises.OrderBy(x=>x.Nombre);
                return View(vm);
            }
            if (imagen!=null)
            {
                if (imagen.ContentType!="image/jpeg")
                {
                    ModelState.AddModelError("", "Solo se permite la carga de archivos JPG");
                    vm.Paises = Context.Paises.OrderBy(x => x.Nombre);
                    return View(vm);
                }
                if (imagen.Length>1024*1024*5)
                {
                    ModelState.AddModelError("", "No se permite la carga de archivos mayores a 5MB");
                    vm.Paises = Context.Paises.OrderBy(x => x.Nombre);
                    return View(vm);
                }
            }
            Context.Add(vm.Raza);
            Context.SaveChanges();
            //Context.Caracteristicasfisicas.Add(vm.Caracteristicas);
            //Context.SaveChanges();

            if (imagen!=null)
            {
                var path = Host.WebRootPath + "/imgs_perros/" + vm.Raza.Id + "_0.jpg";
                FileStream fs = new FileStream(path, FileMode.Create);
                imagen.CopyTo(fs);
                fs.Close();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id)
        {
            Razas raza = Context.Razas.FirstOrDefault(x=>x.Id==id);
            Caracteristicasfisicas c = Context.Caracteristicasfisicas.FirstOrDefault(x=>x.Id==id);
            if (raza==null)
            {
                return RedirectToAction("Index");
            }
            RazaCRUDViewModel vm = new RazaCRUDViewModel
            {
                Raza = raza, Paises = Context.Paises.OrderBy(x=>x.Nombre)
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Editar(RazaCRUDViewModel vm, IFormFile imagen)
        {
            var raza = Context.Razas.Include(x=>x.Caracteristicasfisicas).FirstOrDefault(x => x.Id == vm.Raza.Id);
            if (raza==null)
            {
                return RedirectToAction("Index");
            }
            if (!Verificacion(vm, out string m))
            {
                ModelState.AddModelError("", m);
                vm.Paises = Context.Paises.OrderBy(x=>x.Nombre);
                return View(vm);
            }
            if (imagen != null)
            {
                if (imagen.ContentType != "image/jpeg")
                {
                    ModelState.AddModelError("", "Solo se permite la carga de archivos JPG");
                    vm.Paises = Context.Paises.OrderBy(x => x.Nombre);
                    return View(vm);
                }
                if (imagen.Length > 1024 * 1024 * 5)
                {
                    ModelState.AddModelError("", "No se permite la carga de archivos mayores a 5MB");
                    vm.Paises = Context.Paises.OrderBy(x => x.Nombre);
                    return View(vm);
                }
            }
            raza.Nombre = vm.Raza.Nombre;
            raza.OtrosNombres = vm.Raza.OtrosNombres;
            raza.IdPais = vm.Raza.IdPais;
            raza.PesoMin = vm.Raza.PesoMin;
            raza.PesoMax = vm.Raza.PesoMax;
            raza.AlturaMin = vm.Raza.AlturaMin;
            raza.AlturaMax = vm.Raza.AlturaMax;
            raza.EsperanzaVida = vm.Raza.EsperanzaVida;

            raza.Caracteristicasfisicas.Cola = vm.Raza.Caracteristicasfisicas.Cola;
            raza.Caracteristicasfisicas.Color = vm.Raza.Caracteristicasfisicas.Color;
            raza.Caracteristicasfisicas.Hocico = vm.Raza.Caracteristicasfisicas.Hocico;
            raza.Caracteristicasfisicas.Patas = vm.Raza.Caracteristicasfisicas.Patas;
            raza.Caracteristicasfisicas.Pelo = vm.Raza.Caracteristicasfisicas.Pelo;

            Context.Update(raza);
            Context.SaveChanges();
            if (imagen != null)
            {
                var path = Host.WebRootPath + "/imgs_perros/" + vm.Raza.Id + "_0.jpg";
                FileStream fs = new FileStream(path, FileMode.Create);
                imagen.CopyTo(fs);
                fs.Close();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Eliminar(int id)
        {
            Razas raza = Context.Razas.FirstOrDefault(x=>x.Id==id);
            if (raza==null)
            {
                return RedirectToAction("Index");
            }
            return View(raza);
        }

        [HttpPost]
        public IActionResult Eliminar(Razas vm)
        {
            Razas raza = Context.Razas.FirstOrDefault(x=>x.Id == vm.Id);
            Caracteristicasfisicas caracteristicas = Context.Caracteristicasfisicas.FirstOrDefault(x => x.Id == vm.Id);
            if (raza==null || caracteristicas==null)
            {
                ModelState.AddModelError("", "No se encontro la rza, puede que no exista o ya haya sido eliminado");
                return View(vm);
            }

            Context.Remove(caracteristicas);
            Context.Remove(raza);
            Context.SaveChanges();

            string path = Host.WebRootPath + "/imgs_perros/" + raza.Id + "_0.jpg";
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Index");
        }

        private bool Verificacion(RazaCRUDViewModel vm, out string mensaje)
        {
            if (string.IsNullOrWhiteSpace(vm.Raza.Nombre))
            {
                mensaje = "Asigne un valor a nombre";
                return false;
            }
            if (string.IsNullOrWhiteSpace(vm.Raza.OtrosNombres))
            {
                vm.Raza.OtrosNombres = "No tiene";
            }
            if (string.IsNullOrWhiteSpace(vm.Raza.Descripcion))
            {
                mensaje = "Asigne una descripcion";
                return false;
            }
            if (vm.Raza.IdPais==0)
            {
                mensaje = "Asigne un pais";
                return false;
            }
            if (vm.Raza.PesoMin==0)
            {
                mensaje = "Asigne el peso mínimo";
                return false;
            }
            if (vm.Raza.PesoMax == 0)
            {
                mensaje = "Asigne el peso máximo";
                return false;
            }
            if (vm.Raza.PesoMin>= vm.Raza.PesoMax)
            {
                mensaje = "El peso minimo debe ser menor al Peso Máximo";
                return false;
            }
            if (vm.Raza.AlturaMin == 0)
            {
                mensaje = "Asigne la altura mínima";
                return false;
            }
            if (vm.Raza.AlturaMax == 0)
            {
                mensaje = "Asigne la altura máxima";
                return false;
            }
            if (vm.Raza.AlturaMin >= vm.Raza.AlturaMax)
            {
                mensaje = "El peso minimo debe ser menor al Peso Máximo";
                return false;
            }
            if (vm.Raza.EsperanzaVida == 0)
            {
                mensaje = "Asigne una esperanza de vida";
                return false;
            }


            mensaje = "";
            return true;
        }
    }
}

U3RazasPerros/Areas/Admin/Views/Razas/Agregar.cshtml
@model U3RazasPerros.Areas.Admin.Models.RazaCRUDViewModel
@{
    ViewData["Title"] = "Agregar";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Agregar Raza</h1>
    <a href="~/Admin/Razas" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Atras
    </a>
</section>
<div id="crudM">
    <form method="post" asp-area="Admin" asp-controller="Razas" asp-action="Agregar" enctype="multipart/form-data">
        <div id="crudAdm">
            <label>Nombre:</label>
            <input type="text" asp-for="Raza.Nombre" required><br>
            <label>Otros Nombres:</label>
            <input type="text" asp-for="Raza.OtrosNombres"><br>
            <label>Pais:</label>
            <select required asp-for="Raza.IdPais" asp-items="@(new SelectList(Model.Paises, "Id", "Nombre"))">
                <option selected value="">Selecciona un pais</option>
            </select><br>
            <label>Peso Mínimo:</label>
            <input asp-for="Raza.PesoMin" type="number" required><br>
            <label>Peso Máximo:</label>
            <input asp-for="Raza.PesoMax" type="number" required><br>
            <label>Altura Mínima:</label>
            <input type="number" asp-for="Raza.AlturaMin" required><br>
            <label>Altura Máxima:</label>
            <input type="number" asp-for="Raza.AlturaMax" required><br>
            <label>Esperanza de vida:</label>
            <input type="number" asp-for="Raza.EsperanzaVida" required><br>
            <label>Patas:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Patas"><br>
            <label>Cola:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Cola"><br>
            <label>Hocico:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Hocico"><br>
            <label>Pelo:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Pelo"><br>
            <label>Color:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Color"><br>
            <label>Descripción:</label>
            <textarea asp-for="Raza.Descripcion" required></textarea>
            <p id="error">
                @Html.ValidationSummary()
            </p>
        </div>
        <div id="crudImg">
            <img id="imagePreview" src="~/imgs_perros/NoPhoto.jpg" alt="Vista previa de la imagen">
            <input type="file" id="fileImage" name="imagen" accept="image/jpeg">
        </div>
        <input type="submit">
    </form>

</div>
<br class="clear" />

<script>
    function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('#imagePreview').src= e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    document.querySelector("#fileImage").addEventListener("change", event => {
        mostrarImagen(event.target)
    });

</script>

U3RazasPerros/Areas/Admin/Views/Razas/Editar.cshtml
@model U3RazasPerros.Areas.Admin.Models.RazaCRUDViewModel
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    ViewData["Title"] = "Editar";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Editar Raza</h1>
    <a href="~/Admin/Razas" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Atras
    </a>
</section>
<div id="crudM">
    <form method="post" asp-area="Admin" asp-controller="Razas" asp-action="Editar" enctype="multipart/form-data">
        <div id="crudAdm">
            <label>Nombre:</label>
            <input type="text" asp-for="Raza.Nombre" required><br>
            <label>Otros Nombres:</label>
            <input type="text" asp-for="Raza.OtrosNombres"><br>
            <label>Pais:</label>
            <select required asp-for="Raza.IdPais" asp-items="@(new SelectList(Model.Paises, "Id", "Nombre"))">
                <option selected value="">Selecciona un pais</option>
            </select><br>
            <label>Peso Mínimo:</label>
            <input asp-for="Raza.PesoMin" type="number" required><br>
            <label>Peso Máximo:</label>
            <input asp-for="Raza.PesoMax" type="number" required><br>
            <label>Altura Mínima:</label>
            <input type="number" asp-for="Raza.AlturaMin" required><br>
            <label>Altura Máxima:</label>
            <input type="number" asp-for="Raza.AlturaMax" required><br>
            <label>Esperanza de vida:</label>
            <input type="number" asp-for="Raza.EsperanzaVida" required><br>
            <label>Patas:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Patas"><br>
            <label>Cola:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Cola"><br>
            <label>Hocico:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Hocico"><br>
            <label>Pelo:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Pelo"><br>
            <label>Color:</label>
            <input type="text" asp-for="Raza.Caracteristicasfisicas.Color"><br>
            <label>Descripción:</label>
            <input asp-for="Raza.Id" hidden />
            <textarea asp-for="Raza.Descripcion" required></textarea>
            <p id="error">
                @Html.ValidationSummary()
            </p>
        </div>
        <div id="crudImg">
            @if (System.IO.File.Exists($"{env.WebRootPath}/imgs_perros/{Model.Raza.Id}_0.jpg"))
            {
                <img id="imagePreview" src="~/imgs_perros/@(Model.Raza.Id)_0.jpg" alt="Vista previa de la imagen">
            }
            else
            {
                <img id="imagePreview" src="~/imgs_perros/NoPhoto.jpg" alt="Vista previa de la imagen">
            }
            <input type="file" id="fileImage" name="imagen" accept="image/jpeg">
        </div>
        <input type="submit" value="Editar">
    </form>

</div>
<br class="clear" />

<script>
    function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('#imagePreview').src = e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    document.querySelector("#fileImage").addEventListener("change", event => {
        mostrarImagen(event.target)
    });

</script>

U3RazasPerros/Areas/Admin/Views/Razas/Eliminar.cshtml
@model U3RazasPerros.Models.Razas;
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    ViewData["Title"] = "Eliminar";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Eliminar Raza</h1>
    <a href="~/Admin/Razas" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Atras
    </a>
</section>
<div id="crudM" style=" display: block; width: 50%; margin: auto; left: 20%; position: relative;">
    <div id="crudImg" style="top: 15%; width: 100%; display: block; position: absolute;">
        @if (System.IO.File.Exists($"{env.WebRootPath}/imgs_perros/{Model.Id}_0.jpg"))
        {
            <img id="imagePreview" src="~/imgs_perros/@(Model.Id)_0.jpg" alt="Vista previa de la imagen">
        }
        else
        {
            <img id="imagePreview" src="~/imgs_perros/NoPhoto.jpg" alt="Vista previa de la imagen">
        }
    </div>
    <p style="width: 100%; text-align: center; font-size: larger; display: block; position: absolute;">¿Seguro de eliminar a la raza @(Model.Nombre)?</p>
    <p>
        @Html.ValidationSummary()
    </p>
    <form method="post" asp-area="Admin" asp-controller="Razas" asp-action="Eliminar">
        <input asp-for="Nombre" value="@(Model.Nombre)" hidden />
        <input asp-for="Id" value="@(Model.Id)" hidden />
        <input style="width:100%" type="submit" value="Eliminar">
    </form>

</div>


<br class="clear" />

U3RazasPerros/Areas/Admin/Views/Razas/Index.cshtml
@model IEnumerable<U3RazasPerros.Models.Razas>
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    ViewData["Title"] = "Index";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Razas</h1>
    <a href="~/Admin/Razas/Agregar" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Agregar
    </a>
</section>
<section class="list" id="listAdm">
    <ul>
        @foreach (var r in Model)
        {
            <li>
                <div id="idBox">
                    @if (System.IO.File.Exists($"{env.WebRootPath}/imgs_perros/{r.Id}_0.jpg"))
                    {
                        <img src="/imgs_perros/@(r.Id)_0.jpg" />
                    }
                    else
                    {
                        <img src="/imgs_perros/NoPhoto.jpg" />
                    }
                    <b>Nombre: </b>@r.Nombre<br>
                    <b>Esperanza: </b>@(r.EsperanzaVida) años<br>
                    <b>Peso: </b>@(r.PesoMin)kg <b>-</b> @(r.PesoMax)kg<br>
                    <b>Altura: </b>@(r.AlturaMin)cm <b>-</b> @(r.AlturaMax)cm
                    <div class="btnAdm">
                        <a href="~/Admin/Razas/Editar/@(r.Id)">Editar</a>
                        <a href="~/Admin/Razas/Eliminar/@(r.Id)">Eliminar</a>
                    </div>
                </div>
            </li>
        }
    </ul>
</section>