U3RazasPerros/Areas/Admin/Controllers/PaisesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using U3RazasPerros.Models;

namespace U3RazasPerros.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PaisesController : Controller
    {
        public PaisesController(perrosContext context)
        {
            Context = context;
        }

        public perrosContext Context { get; }

        public IActionResult Index()
        {
            IEnumerable<Paises> paises = Context.Paises.OrderBy(x=>x.Nombre);
            return View(paises);
        }

        public IActionResult Agregar()
        {
            return View(new Paises());
        }

        [HttpPost]
        public IActionResult Agregar(Paises p)
        {
            if (string.IsNullOrWhiteSpace(p.Nombre))
            {
                ModelState.AddModelError("", "Agregue un nombre al pais");
                return View(p);
            }
            if (Context.Paises.Any(x=>x.Nombre==p.Nombre))
            {
                ModelState.AddModelError("", "Ya existe un pais con ese nombre");
                return View(p);
            }
            Context.Paises.Add(p);
            Context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id)
        {
            Paises pais = Context.Paises.FirstOrDefault(x=>x.Id==id);
            if (pais==null)
            {
                return RedirectToAction("Index");
            }
            return View(pais);
        }

        [HttpPost]
        public IActionResult Editar(Paises p)
        {
            if (string.IsNullOrWhiteSpace(p.Nombre))
            {
                ModelState.AddModelError("", "Agregue un nombre al pais");
                return View(p);
            }
            if (Context.Paises.Any(x => x.Nombre == p.Nombre))
            {
                ModelState.AddModelError("", "Ya existe un pais con ese nombre");
                return View(p);
            }
            Paises pais = Context.Paises.FirstOrDefault(x=>x.Id == p.Id);
            pais.Nombre = p.Nombre;
            Context.Paises.Update(pais);
            Context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Eliminar(int id)
        {
            Paises p = Context.Paises.FirstOrDefault(x=>x.Id == id);
            if (p == null)
            {
                return RedirectToAction("Index");
            }
            return View(p);
        }

        [HttpPost]
        public IActionResult Eliminar(Paises p)
        {
            Paises pais = Context.Paises.FirstOrDefault(x=>x.Id == p.Id);
            if (pais==null)
            {
                ModelState.AddModelError("", "No se encontro el pais, puede que no exista o ya haya sido eliminado");
                return View(pais);
            }
            if (Context.Razas.Any(x=>x.IdPais==p.Id))
            {
                ModelState.AddModelError("", "No se puede eliminar este pais porque hay razas registrados con este pais");
                return View(pais);
            }
            Context.Paises.Remove(pais);
            Context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

U3RazasPerros/Areas/Admin/Views/Paises/Agregar.cshtml
@model U3RazasPerros.Models.Paises
@{
    ViewData["Title"] = "Agregar";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Agregar Pais</h1>
    <a href="~/Admin/Paises" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Atras
    </a>
</section>
<div id="crudM" style="height: auto; display: block; width: 50%; margin: auto; left: 20%; position: relative;">
    <div id="crudImg" style="top: 15%; width: 100%; display: block; position: absolute;">
    </div>

    <form method="post" asp-area="Admin" asp-controller="Paises" asp-action="Agregar">
        <div style="height: 25px; position: relative; background-color: #247eb0; margin: 5px 0; border: 1px solid black; padding: 5px;">
            <label style="color: white; display: inline-block; width: 40%;">Nombre del Pais:</label>
            <div style=" right:0; display: inline-block; width: 50%;  position: absolute;">
                <input style="border: 2px solid saddlebrown;
        width: 80%;
        left: 0;
        top: 0;
        font-size: medium;
        position: absolute;" asp-for="Nombre" type="text">
            </div>
        </div>
        <p>
            @Html.ValidationSummary()
        </p>
        <input style="position: relative; width:100%; margin: 10px 0;" type="submit" value="Agregar">
    </form>

</div>


<br class="clear" />

U3RazasPerros/Areas/Admin/Views/Paises/Editar.cshtml
@model U3RazasPerros.Models.Paises
@{
    ViewData["Title"] = "Editar";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Editar Pais</h1>
    <a href="~/Admin/Paises" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Atras
    </a>
</section>
<div id="crudM" style="height: auto; display: block; width: 50%; margin: auto; left: 20%; position: relative;">
    <div id="crudImg" style="top: 15%; width: 100%; display: block; position: absolute;">
    </div>

    <form method="post" asp-area="Admin" asp-controller="Paises" asp-action="Editar">
        <div style="height: 25px; position: relative; background-color: #247eb0; margin: 5px 0; border: 1px solid black; padding: 5px;">
            <label style="color: white; display: inline-block; width: 40%;">Nombre del Pais:</label>
            <div style=" right:0; display: inline-block; width: 50%;  position: absolute;">
                <input style="border: 2px solid saddlebrown;
        width: 80%;
        left: 0;
        top: 0;
        font-size: medium;
        position: absolute;" asp-for="Nombre" type="text">
            </div>
        </div>
        <p>
            @Html.ValidationSummary()
        </p>
        <input asp-for="Id" value="@Model.Id" hidden />
        <input style="position: relative; width:100%; margin: 10px 0;" type="submit" value="Editar">
    </form>

</div>


<br class="clear" />

U3RazasPerros/Areas/Admin/Views/Paises/Eliminar.cshtml
@model U3RazasPerros.Models.Paises
@{
    ViewData["Title"] = "Eliminar";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Eliminar Pais</h1>
    <a href="~/Admin/Paises" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Atras
    </a>
</section>
<div id="crudM" style="height: auto; display: block; width: 50%; margin: auto; left: 20%; position: relative;">
    <div id="crudImg" style="top: 15%; width: 100%; display: block; position: absolute;">
    </div>

    <form method="post" asp-area="Admin" asp-controller="Paises" asp-action="Eliminar">
        <div style="height: 25px; position: relative; background-color: #247eb0; margin: 5px 0; border: 1px solid black; padding: 5px;">
            <label style="text-align:center; color: white; display: inline-block; width: 100%;">¿Estas seguro de eliminar @(Model.Nombre)?</label>
            
        </div>
        <p>
            @Html.ValidationSummary()
        </p>
        <input asp-for="Id" value="@Model.Id" hidden />
        <input style="position: relative; width:100%; margin: 10px 0;" type="submit" value="Eliminar">
    </form>

</div>


<br class="clear" />

U3RazasPerros/Areas/Admin/Views/Paises/Index.cshtml
@model IEnumerable<U3RazasPerros.Models.Paises>
@{
    ViewData["Title"] = "Index";
    Layout = "MasterPageAdmin";
}

<section style="position: relative; width: 100%; height: 40px; float: left; margin: 5px 0;">
    <h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Paises</h1>
    <a href="~/Admin/Paises/Agregar" style="text-decoration: none; width: 15%; text-align: center; display: block; padding: 3px; background-color: saddlebrown; color: white; border: 1px solid black; position: absolute; right: 0;">
        Agregar
    </a>
</section>
<div id="crudM" style="height:auto; display: block; width: 50%; margin: auto; left: 20%; position: relative;">
    <div id="crudImg" style="top: 15%; width: 100%; display: block; position: absolute;">
    </div>
    @foreach (var p in Model)
    {
        <div style="position: relative; background-color: #247eb0; margin: 5px 0; border: 1px solid black; padding: 5px;">
            <label style="color: white; display: inline-block; width: 40%;">@p.Nombre</label>
            <div style=" right:0; display: inline-block; width: 40%;  position: absolute;">
                <a style="text-align: center; color: white; text-decoration: none; width: 45%; display: inline-block; background-color: saddlebrown; border: 1px solid black;" href="~/Admin/Paises/Editar/@(p.Id)">Editar</a>
                <a style="text-align: center; color: white; text-decoration: none; width: 45%; display: inline-block; background-color: saddlebrown; border: 1px solid black;" href="~/Admin/Paises/Eliminar/@(p.Id)">Eliminar</a>
            </div>
        </div>
    }
</div>
<br class="clear" />